# Production Environment Configuration (与预发一致的模式，地址通过环境变量区分)
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:integrated_services}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456789}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}

  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER:localhost:8848}
      config:
        enabled: true
        server-addr: ${NACOS_SERVER:localhost:8848}

logging:
  level:
    root: WARN
    com.enterprise.integrated: INFO
    org.springframework.security: WARN
  file:
    name: /var/log/integrated-services/application.log

knife4j:
  enable: false
  production: true

spring.cloud.sentinel:
  enabled: true
  transport:
    dashboard: ${SENTINEL_DASHBOARD:localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: never
