# Test (本地开发同 test 使用)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/integrated-services-test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456789
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      validation-query: SELECT 1
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: ${DRUID_PASSWORD:admin123}

  data:
    redis:
      host: localhost
      port: 6379
      database: 1

  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2

  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false

logging:
  level:
    root: INFO
    com.enterprise.integrated: DEBUG
    org.springframework.security: DEBUG

knife4j:
  enable: true
  production: false

spring.cloud.sentinel:
  enabled: false


