# Development Environment Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/integrated_services_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 1

  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false

# Logging for Development
logging:
  level:
    root: INFO
    com.enterprise.integrated: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.baomidou.mybatisplus: DEBUG

# Knife4j for Development
knife4j:
  enable: true
  production: false

# Sentinel for Development
spring.cloud.sentinel:
  enabled: false
